accessTokenLifeTime: 86400000
dataLoaderMode: never
refreshTokenLifeTime: 172900000
server:
    port: 8084
spring:
    datasource:
        password: 1
        url: jdbc:postgresql://localhost:5432/debtbook
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
        show-sql: true
    sql:
        init:
            mode: never
tokenSecretKey: 9OhGa*6i6RiB5!~mg@w"fidFi1iuc736287-syufbujnc~0A@D
